
<div class="row-fluid">
	<div class="col-md-2" >
		<a href="#"><strong><i class="glyphicon glyphicon-dashboard"></i> Add
		Media</strong>
</a>

	</div>
	<div class="col-md-10" >
	<div class="progress progress-striped ">
	<div class="progress-bar progress-bar-info"" role="progressbar" aria-valuenow="0"
		aria-valuemin="0" aria-valuemax="100" id="mediaProgress">
		<span class="sr-only">60% Complete</span>
	</div>
	</div>
</div>

</div>
<div class="row-fluid">
<div class="col-md-12">
<!--FILE DROP ZONE-->
<div id="dropzone" class="well" style="text-align: center;
height: 150px;
vertical-align: middle;
padding-top: 50px;">
	<span class="glyphicon glyphicon-import"
		style="font-size: 30px; text-align: center">Drop Files Here</span>
</div>


<!-- The file input field used as target for the file upload widget -->
<!-- <input id="fileupload" type="file" class="pull-right" name="files[]" multiple> -->
<input type="file" class="filestyle pull-right" data-classButton="btn btn-primary" id="fileupload" name="files[]" data-input="false">
<div style="clear:both">&nbsp</div>


<!-- The list of files uploaded -->
<p>Files uploaded:</p>
<div id="files"></div>
</div>
</div>


<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script
	src="<?php echo $this->url->get('public/js/jquery.ui.widget.js');?>"></script>
<script
	src="<?php echo $this->url->get('public/js/jquery.iframe-transport.js');?>"></script>
<script
	src="<?php echo $this->url->get('public/js/jquery.fileupload.js');?>"></script>
<script
	src="<?php echo $this->url->get('public/js/jquery.fileupload-video.js');?>"></script>

<script
	src="<?php echo $this->url->get('public/js/jquery.fileupload-process.js');?>"></script>

<script>
/*jslint unparam: true */
/*global window, $ */
$(function () {
    'use strict';
    // Change this to the location of your server-side upload handler:
    var url = window.location.hostname === 'blueimp.github.io' ?
                '//jquery-file-upload.appspot.com/' : 'http://localhost:8888/unic/dashboard/uploadMedia';
    $('#fileupload').fileupload({
        url: url,
        dataType: 'json',
        maxChunkSize: 10000000,
        done: function (e, data) {
            $.each(data.result.files, function (index, file) 
                    {
               var tag='<img src="'+file.url+'" height="200" width="200" class="img-thumbnail"/>';
                $(tag).appendTo('#files');
            });
            
        },
        progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.progress-bar').css(
                'width',
                progress + '%'
            );
        },
        complete:function(){
        	$("#mediaProgress").removeClass('progress-bar-info');
            $("#mediaProgress").addClass('progress-bar-success');
            
        },
        //Enable file drag drop
        dropZone: $('#dropzone') 
    }).prop('disabled', !$.support.fileInput)
        .parent().addClass($.support.fileInput ? undefined : 'disabled');
});
$('#fileupload').bind('fileuploadprogress', function (e, data) {
    // Log the current bitrate for this upload:
    console.log(data.bitrate);
});
$(document).bind('dragover', function (e) {
    var dropZone = $('#dropzone'),
        timeout = window.dropZoneTimeout;
    if (!timeout) {
        dropZone.addClass('in');
    } else {
        clearTimeout(timeout);
    }
    var found = false,
      	node = e.target;
    do {
        if (node === dropZone[0]) {
       		found = true;
       		break;
       	}
       	node = node.parentNode;
    } while (node != null);
    if (found) {
        dropZone.addClass('hover');
    } else {
        dropZone.removeClass('hover');
    }
    window.dropZoneTimeout = setTimeout(function () {
        window.dropZoneTimeout = null;
        dropZone.removeClass('in hover');
    }, 100);
});
</script>
