<div class="row-fluid">
<!--  --><?php //echo $module->moduleName;?>
<!--    --><?php //echo "<pre>"; print_r($module); ?>
    <form class="form-horizontal" action="<?php echo $this->url->get(array('for'=>'AddQuestions')); ?>" method="post" enctype="multipart/form-data">
        <fieldset>

            <!-- Form Name -->
            <legend>Create Question</legend>
            <!--   Select Test  -->

            <div class="form-group">
                <label class="col-md-2 control-label" for="test_id">Test:</label>
                <div class="col-md-9">
                    <?php
                    echo Phalcon\Tag::select(
                      array(
                          "test_id",
                          \Unic\Models\Test::find(),
                          'useEmpty'  =>  true,
                          'emptyText' =>  'Select Test',
                          "using"=>array("test_id","testName"),
                          "class"=>"form-control"
                      )
                    );
                    ?>
                    </div>
                </div>
            <!-- End Select test-->
            <!-- Select Module -->
            <div class="form-group">
                <label class="col-md-2 control-label" for="questionModuleID">Module:</label>
                <div class="col-md-9">
                    <?php
                    echo Phalcon\Tag::select(
                            array(
                                "questionModuleID",
                                array(null=>'Select Module'),
                                "class"=>"form-control"
                            ));
                     ?>
                </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-2 control-label" for="questionText">Question:</label>
                <div class="col-md-9">
                    <textarea class="ckeditor " id="questionText" name="questionText"></textarea>
                </div>
            </div>

            <!-- option input-->
            <?php $i = 1; $count = 5; for($i;$i<=$count;$i++){ ?>
            <div class="form-group">
                <label class="col-md-2 control-label" for="option">Option <?php echo $i; ?>:</label>
                <div class="col-md-7">
                    <input type="text" name="questionOptions[]" placeholder="Options" class="form-control input-md">
                </div>
                <div class="col-md-2">
                    <input type="text" name="questionMarks[]" placeholder="Marks" class="form-control input-md">
                </div>
            </div>
            <?php } ?>


            <!-- Button (Double) -->
            <div class="form-group">
                <label class="col-md-2 control-label" for="submit"></label>
                <div class="col-md-9">
                    <button id="submit" name="submit" type="submit" class="btn btn-primary btn-block">Save</button>

                </div>
            </div>


        </fieldset>
    </form>
</div>
<script type="application/javascript">
    var getResultUrl="<?php echo $this->url->get(array("for"=>"GetModuleByTestID")); ?>";
    </script>
<script type="text/javascript">
$('#test_id').change(function(){
    var value=$(this).val();

    $.ajax({
        type:"POST",
        url:getResultUrl,
        data:{"id":value},

        success:function(response){

            $("#questionModuleID option")
                .not(":first").remove();

             var parsed= $.parseJSON(response);

            $.each(parsed,function(key,value){
                $("#questionModuleID")
                    .append($("<option></option>")
                    .attr("value",value.id)
                    .text(value.name));

            });
        }
    });
});
</script>
