<style>
    #wrapper .text {
        position: relative;
        bottom: 20px;
        left: 0px;
        visibility: hidden;
    }

    #wrapper:hover .text {
        visibility: visible;
    }
</style>
<div class="row-fluid">
    <div class="col-md-12 col-sm-12">
        <!--Page Title-->
        <div class="page-title">
            <h2><i class="color" style=""></i>Add Courses Description</h2>
            <hr/>
        </div>
        <!-- /Page title -->

    </div>
</div>
<div class="row-fluid" ng-app="unic" ng-controller="CourseCtrl">
  <div class="col-md-6">
      <?php if (isset($error)) {
          echo "<p style='color: red'>$error</p>";
      } elseif (isset($course_id)) {
          ?>

          <form class="form-horizontal" id="title" name="title" enctype="multipart/form-data" action=""
                ng-submit="addCourseDescription('/course/createCourseDescription')"
                ng-init="form.courseID='<?php echo $course_id; ?>'">
              <fieldset>
                  <input type="hidden" name="courseId" ng-model="form.courseID" ng-value="form.courseID">
                  <!-- Description -->
                  <br/>

                  <div class="form-group">
                      <label class="col-md-2 control-label" for="description">Description</label>

                      <div class="col-md-9">
                          <textarea id="description" name="description" ng-model="form.description"
                                    class="form-control input-md"></textarea>
                      </div>
                  </div>

                  <!-- Estimated Effort-->

                  <div class="form-group">
                      <label class="col-md-2 control-label" for="estimated_effort">Estimated Effort</label>

                      <div class="col-md-9">
                          <input id="estimated_effort" name="estimated_effort" placeholder="Estimated Effort"
                                 class="form-control input-md" type="text" ng-model="form.estimated_effort">
                      </div>
                  </div>

                  <!-- Length -->

                  <div class="form-group">
                      <label class="col-md-2 control-label" for="length">Length</label>

                      <div class="col-md-9">
                          <input id="length" name="length" placeholder="Length" class="form-control input-md" type="text"
                                 ng-model="form.length">
                      </div>
                  </div>

                  <!-- About-->

                  <div class="form-group">
                      <label class="col-md-2 control-label" for="about">About</label>

                      <div class="col-md-9">
                          <textarea id="about" name="about" ng-model="form.about"
                                    class="form-control input-md"></textarea>
                      </div>
                  </div>
                  <!-- Button -->
                  <div class="form-group">
                      <div class="col-md-2">

                      </div>

                      <div class="col-md-9">

                          <button type="submit" name="submit" class="btn btn-primary btn-block">Save</button>
                      </div>
                  </div>
              </fieldset>
          </form>
      <?php
      } elseif ($CourseSpec) {
      ?>
      <?php foreach ($CourseSpec as $Course) { ?>
      <form class="form-horizontal" action="" ng-submit="addCourseDescription('/course/updateCourseDescription')"
            ng-init="form.length='<?php echo $Course[ "length" ] ?>';
                     form.effort='<?php echo $Course[ "effort" ] ?>';
                     form.description='<?php echo $Course[ "description" ] ?>';
                     form.courseID='<?php echo $Course[ "specID" ] ?>';
                     form.about='<?php echo $Course[ "about" ] ?>'">
          <fieldset>
              <input type="hidden" name="course_id" ng-model="form.courseID" ng-value="form.courseID">
              <!-- Description -->
              <br/>

              <div class="form-group">
                  <label class="col-md-2 control-label" for="description">Description</label>

                  <div class="col-md-9">
                      <textarea id="description" name="description" ng-model="form.description"
                                class="form-control input-md"><?php echo $Course[ 'description' ]; ?>
                          [[form.description]]</textarea>
                  </div>
              </div>
              <!--Estimated Effort-->
              <div class="form-group">
                  <label class="col-md-2 control-label" for="estimated_effort">Estimated Effort</label>

                  <div class="col-md-9">
                      <input class="form-control input-md" id="estimated_effort" ng-model="form.effort"
                             ng-value="form.effort">
                  </div>
              </div>

              <!-- Length -->

              <div class="form-group">
                  <label class="col-md-2 control-label" for="length">Length</label>

                  <div class="col-md-9">
                      <input id="length" name="length" class="form-control input-md" type="text"
                             ng-model="form.length" ng-value="form.length">
                  </div>
              </div>

              <!-- About-->

              <div class="form-group">
                  <label class="col-md-2 control-label" for="about">About</label>

                  <div class="col-md-9">
                      <textarea id="about" name="about" ng-model="form.about" class="form-control input-md">[[form.about]]</textarea>
                  </div>
              </div>
              <!-- Button -->
              <div class="form-group">
                  <div class="col-md-2">
                  </div>
                  <div class="col-md-9">
                      <button type="submit" name="submit" class="btn btn-primary btn-block">Save</button>
                  </div>
              </div>
          </fieldset>
      </form>
  </div>
        <?php } ?>
    <?php } ?>
</div>


<script src="<?php echo $this->url->get ('public/js/admin/app.js'); ?>"></script>
<script src="<?php echo $this->url->get ('public/js/admin/controller.js'); ?>"></script>
