
<div class="page-title col-md-6 col-sm-6">
    <h2><i class="color" style=""></i> Uploaded Videos </h2>
</div>
<div class="col-sm-6 col-md-6">
    <form class="navbar-form" role="search">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="q">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
    </form>
</div>
<hr>

<table class="table table-hover table-bordered col-lg-12 col-sm-12 col-md-12" >
    <thead>
    <tr>
        <th>#</th>
        <th>Filename</th>
        <th>Date</th>
        <th>Status</th>
    </tr>
    </thead>
    <tbody>
    <?php if($media){ foreach($media as $key){?>
        <tr>
            <td><?php echo $key['id'];?></td>
            <td><?php echo $key['filename'];?></td>
            <td><?php echo $key['uploadedAt'];?></td>
            <td><?php  echo $key['verified']==0 ? 'Processing' : 'Verified' ;?></td>
        </tr>
    <?php } }?>
    </tbody>
</table>
