<style type="text/css">


    .fileinput-button {
        position: relative;
        overflow: hidden;
    }
    .fileinput-button input {
        position: absolute;
        top: 0;
        right: 0;
        margin: 0;
        opacity: 0;
        -ms-filter: 'alpha(opacity=0)';
        font-size: 100px;
        direction: ltr;
        cursor: pointer;
    }

        /* Fixes for IE < 8 */
    @media screen\9 {
        .fileinput-button input {
            filter: alpha(opacity=0);
            font-size: 90%;
            height: 90%;
        }
    }

</style>
<div class="page-title col-md-3 col-sm-3">
    <h2><i class="color" style=""></i> Upload Media </h2>
</div>
<!--File Input button-->
<div class="col-md-2" style="padding-top: 8px">
    <span class="btn btn-success fileinput-button pull-left input-sm">
<i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input name="files[]" multiple="" type="file" id="fileupload" data-sequential-uploads="true">
                </span>
</div>
<div class="col-sm-6 col-md-6" style="padding-top: 10px">
    <div class="progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">

        </div>
    </div>

</div>
<div class="row-fluid" id="gallery">



</div>

<div class="row-fluid">
    <div class="col-md-12">        <!-- The file input field used as target for the file upload widget -->
        <!-- <input id="fileupload" type="file" class="pull-right" name="files[]" multiple> -->
        <div style="clear:both">&nbsp</div>

    </div>


</div>


<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script
    src="<?php echo $this->url->get('public/js/jquery.ui.widget.js');?>"></script>
<script
    src="<?php echo $this->url->get('public/js/jquery.iframe-transport.js');?>"></script>
<script
    src="<?php echo $this->url->get('public/js/jquery.fileupload.js');?>"></script>
<script
    src="<?php echo $this->url->get('public/js/jquery.fileupload-video.js');?>"></script>

<script
    src="<?php echo $this->url->get('public/js/jquery.fileupload-process.js');?>"></script>

<script>
    /*jslint unparam: true */
    /*global window, $ */
    $(function () {
        'use strict';
        // Change this to the location of your server-side upload handler:
        var url = window.location.hostname === 'blueimp.github.io' ?
            '//jquery-file-upload.appspot.com/' : 'http://localhost/unic/dashboard/saveMedia';
        $('#fileupload').fileupload({
            url: url,
            dataType: 'json',
            maxChunkSize: 10000000,
            add:function(e,data)
            {
                $.each(data.files, function (index, file)
                 {
                    $("#gallery").append("<div class='col-sm-6 col-md-3 thumbcontainer'><div class='thumbnail'>" +
                        "<div class='caption"+index+"'></div>" +
                        "</div>" +
                        "</div>");
                    data.context=$('<button/>').text('Upload')
                        .appendTo(".thumbcontainer:last .caption")
                        .click(function ()
                        {
                            data.context = $('<p/>').text('Uploading...').replaceAll($(this));



                        });
                     data.submit();
                  });
            },
            done: function (e, data)
            {
                $.each(data.result.files, function (index, file)
                {
                    var tag='<img src="'+file.url+'" height="200" width="200" class="img-thumbnail"/>';
                    $(tag).appendTo('#files');
                });

            },
            progress:function(e,data)
            {

            },
            progressall: function (e, data)
            {
                var progress = parseInt(data.loaded / data.total * 100, 10);
                $('.progress-bar').css(
                    'width',
                    progress + '%'
                );
            },
            complete:function(){
                $("#mediaProgress").removeClass('progress-bar-info');
                $("#mediaProgress").addClass('progress-bar-success');

            },
            //Enable file drag drop
            dropZone: $('#dropzone')
        }).prop('disabled', !$.support.fileInput)
            .parent().addClass($.support.fileInput ? undefined : 'disabled');
    });
    $('#fileupload').bind('fileuploadprogress', function (e, data) {
        // Log the current bitrate for this upload:
    });
    $(document).bind('dragover', function (e) {
        var dropZone = $('#dropzone'),
            timeout = window.dropZoneTimeout;
        if (!timeout) {
            dropZone.addClass('in');
        } else {
            clearTimeout(timeout);
        }
        var found = false,
            node = e.target;
        do {
            if (node === dropZone[0]) {
                found = true;
                break;
            }
            node = node.parentNode;
        } while (node != null);
        if (found) {
            dropZone.addClass('hover');
        } else {
            dropZone.removeClass('hover');
        }
        window.dropZoneTimeout = setTimeout(function () {
            window.dropZoneTimeout = null;
            dropZone.removeClass('in hover');
        }, 100);
    });
</script>