<link rel="stylesheet" href="<?php echo $this->url->get('public/css/style.css');?>"/>
<!-- blueimp Gallery styles -->
	<div class="page-header">
		<h3>Upload Videos</h3>
	</div>
        <!-- Button to select & upload files -->
  <span class="btn btn-success fileinput-button">
    <!-- The file input field used as target for the file upload widget -->
    <input id="fileupload" type="file" name="files[]" multiple>
  </span>
  
  
  <!-- The global progress bar -->
  <p>Upload progress</p>
  
  <div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
    <span class="sr-only">60% Complete</span>
  </div>
</div>

  <!--FILE DROP ZONE-->
  <div id="dropzone" class="fade well">Drop files here</div>
  <!-- The list of files uploaded -->
  <p>Files uploaded:</p>
  <ul id="files"></ul>
  
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="<?php echo $this->url->get('public/js/jquery.ui.widget.js');?>"></script>
<script src="<?php echo $this->url->get('public/js/jquery.iframe-transport.js');?>"></script>
<script src="<?php echo $this->url->get('public/js/jquery.fileupload.js');?>"></script>
<script src="<?php echo $this->url->get('public/js/jquery.fileupload-video.js');?>"></script>
<script src="<?php echo $this->url->get('public/js/jquery.fileupload-process.js');?>"></script>


<script>
/*jslint unparam: true */
/*global window, $ */
$(function () {
    'use strict';
    // Change this to the location of your server-side upload handler:
    var url = window.location.hostname === 'blueimp.github.io' ?
                '//jquery-file-upload.appspot.com/' : 'http://localhost:8888/unic/dashboard/saveVideo';
    $('#fileupload').fileupload({
        url: url,
        dataType: 'json',
        done: function (e, data) {
            $.each(data.result.files, function (index, file) {
                $('<p/>').text(file.name).appendTo('#files');
            });
        },
        progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.progress-bar').css(
                'width',
                progress + '%'
            );
        },
        //Enable file drag drop
        dropZone: $('#dropzone') 
    }).prop('disabled', !$.support.fileInput)
        .parent().addClass($.support.fileInput ? undefined : 'disabled');
});
$('#fileupload').bind('fileuploadprogress', function (e, data) {
    // Log the current bitrate for this upload:
    console.log(data.bitrate);
});
$(document).bind('dragover', function (e) {
    var dropZone = $('#dropzone'),
        timeout = window.dropZoneTimeout;
    if (!timeout) {
        dropZone.addClass('in');
    } else {
        clearTimeout(timeout);
    }
    var found = false,
      	node = e.target;
    do {
        if (node === dropZone[0]) {
       		found = true;
       		break;
       	}
       	node = node.parentNode;
    } while (node != null);
    if (found) {
        dropZone.addClass('hover');
    } else {
        dropZone.removeClass('hover');
    }
    window.dropZoneTimeout = setTimeout(function () {
        window.dropZoneTimeout = null;
        dropZone.removeClass('in hover');
    }, 100);
});
</script>