<style type="text/css">
   .thumbnail .caption{font-size: 14px;font-weight: bold;}
</style>
<div class="page-title col-md-6 col-sm-6">
    <h2><i class="color" style=""></i> Upload Videos </h2>
</div>
<div class="col-sm-6 col-md-6">
    <form class="navbar-form" role="search">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="q">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
    </form>
</div>
<hr>
<div class="row-fluid" id="gallery">



</div>
<!--<div id="dropzone" class="well" style="text-align: center;height: 150px;vertical-align: middle;padding-top: 50px;">-->
<!--    <span class="glyphicon glyphicon-import" style="font-size: 30px; text-align: center">Drop Files Here</span>-->
<!--</div>-->
<div class="row-fluid">
    <div class="col-md-12">        <!-- The file input field used as target for the file upload widget -->
        <!-- <input id="fileupload" type="file" class="pull-right" name="files[]" multiple> -->
        <input type="file" class="filestyle pull-right" data-classButton="btn btn-primary" id="fileupload" name="files[]" data-input="false" multiple="multiple">
        <div style="clear:both">&nbsp</div>
    </div>
</div>


<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script
    src="<?php echo $this->url->get('public/js/jquery.ui.widget.js');?>"></script>
<script
    src="<?php echo $this->url->get('public/js/jquery.iframe-transport.js');?>"></script>
<script
    src="<?php echo $this->url->get('public/js/jquery.fileupload.js');?>"></script>
<script
    src="<?php echo $this->url->get('public/js/jquery.fileupload-video.js');?>"></script>

<script
    src="<?php echo $this->url->get('public/js/jquery.fileupload-process.js');?>"></script>

<script>
    /*jslint unparam: true */
    /*global window, $ */
    $(function () {
        'use strict';
        // Change this to the location of your server-side upload handler:
        var url = window.location.hostname === 'blueimp.github.io' ?
            '//jquery-file-upload.appspot.com/' : 'http://localhost/unic/dashboard/saveMedia';
        $('#fileupload').fileupload({
            url: url,
            dataType: 'json',
            maxChunkSize: 1000000,
            add: function (e, data)
            {
                $("#gallery").append("<div class='col-sm-6 col-md-3 thumbcontainer'><div class='thumbnail'>" +
                                     "<img src=''>"+
                                     "<div class='caption'><h3>"+'Starting Upload' + '</h3>'+
                                      "<a class='btn btn-success'>Update</a><a class='btn btn-danger'>Delete</a>"  +'</div>' +
                                     "</div>+" +
                                     "</div>");
                data.submit();
            },
            done: function (e, data) {
                $.each(data.result.files, function (index, file)
                {
                    var tag='<img src="'+file.url+'" height="200" width="200"/>';
                    var texttag='<input type="text" placeholder="Video Title" class="input-sm form-control focus"> ';
                    //$(tag).appendTo('#files');
                   $(".thumbcontainer:last").children('.thumbnail').children("img").attr('src',file.url);
                   $(".thumbcontainer:last").children('.thumbnail').children('.caption').children('h3').html(texttag);

                });

            },
            progressall: function (e, data) {
                var progress = parseInt(data.loaded / data.total * 100, 10);

                $(".thumbcontainer:last").children('.thumbnail').children('.caption').children('h3').html("Uploaded: "+progress + '%' + '<br/>');
                $('.progress-bar').css(
                    'width',
                    progress + '%'
                );
            },
            complete:function(){
                $("#mediaProgress").removeClass('progress-bar-info');
                $("#mediaProgress").addClass('progress-bar-success');

            },
            //Enable file drag drop
            dropZone: $('#dropzone')
        }).prop('disabled', !$.support.fileInput)
            .parent().addClass($.support.fileInput ? undefined : 'disabled');
    });
    $('#fileupload').bind('fileuploadprogress', function (e, data)
    {
        // Log the current bitrate for this upload:
    });
    $(document).bind('dragover', function (e) {
        var dropZone = $('#dropzone'),
            timeout = window.dropZoneTimeout;
        if (!timeout) {
            dropZone.addClass('in');
        } else {
            clearTimeout(timeout);
        }
        var found = false,
            node = e.target;
        do {
            if (node === dropZone[0]) {
                found = true;
                break;
            }
            node = node.parentNode;
        } while (node != null);
        if (found) {
            dropZone.addClass('hover');
        } else {
            dropZone.removeClass('hover');
        }
        window.dropZoneTimeout = setTimeout(function () {
            window.dropZoneTimeout = null;
            dropZone.removeClass('in hover');
        }, 100);
    });
</script>