
<div class="page-title col-md-6 col-sm-6">
    <h2><i class="color" style=""></i> View Questions </h2>
</div>
<div class="col-sm-6 col-md-6">
    <form class="navbar-form" role="search">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="q">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
    </form>
</div>
<hr>
<?php //echo "<pre>";print_r($question); ?>
<?php if(isset($_GET['q'])){

} ?>
<div class="col-lg-12 col-md-12 col-sm-12">
<table class="table table-hover table-bordered col-lg-12 col-sm-12 col-md-12" >
    <thead>
    <tr>
        <th>#</th>
        <th>QuestionName</th>
        <th>Module Name</th>
        <th>Controls</th>
    </tr>
    </thead>
    <tbody>
    <?php $i=1; if($question){ foreach($question->items as $value){ ?>
    <tr>
        <td><?php echo $i; $i++; ?></td>
        <td><?php echo $value->questionText; ?></td>
        <td><?php echo $value->moduleName; ?></td>
        <td>
            <button class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> </button>
            <button class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> </button>
        </td>
    </tr>
    <?php }} ?>
</tbody>
    </table>
<a href="<?php echo $this->url->get('dashboard/viewQuestions') ?>">First</a>&nbsp;&nbsp;&nbsp;
<a href="<?php echo $this->url->get('dashboard/viewQuestions').'?page='.$question->before; ?>" >Previous</a>&nbsp;&nbsp;&nbsp;
<a href="<?php echo $this->url->get('dashboard/viewQuestions').'?page='.$question->next; ?>">Next</a>&nbsp;&nbsp;&nbsp;
<a href="<?php echo $this->url->get('dashboard/viewQuestions').'?page='.$question->last; ?>">Last</a>&nbsp;&nbsp;&nbsp;
<?php echo "You are in page ", $question->current, " of ", $question->total_pages; ?>

</div>