<!--Page Title-->
<div class="page-title">
    <h2><i class="color" style=""></i> View Courses </h2>
    <hr />
</div>
<!-- /Page title -->
<table class="table table-hover table-bordered " >
    <thead>
    <tr>
        <th>#</th>
        <th>CourseName</th>
        <th>CourseID</th>
        <th>Price</th>
        <th>Status</th>
        <th>School</th>
        <th>Controls</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>1</td>
        <td>Flight Vehicle Aerodynamics</td>
        <td>16.110x</td>
        <td>$23</td>
        <td>Active</td>
        <td>MIT</td>
        <td>
            <button class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> </button>
            <button class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> </button>
        </td>
    </tr>
    <tr>
        <td>2</td>
        <td>Computer Science</td>
        <td>U2345</td>
        <td>$22</td>
        <td>Active</td>
        <td>MiTs</td>
        <td>
            <button class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> </button>
            <button class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> </button>
        </td>
    </tr>
    <tr>
        <td>3</td>
        <td>Mech</td>
        <td>UK234</td>
        <td>$43</td>
        <td>Pending</td>
        <td>Mestd</td>
        <td>
            <button class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> </button>
            <button class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> </button>
        </td>
    </tr>
    <tr>
        <td>4</td>
        <td>Mech</td>
        <td>45K234</td>
        <td>$43</td>
        <td>Pending</td>
        <td>Mestd</td>
        <td>
            <button class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> </button>
            <button class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> </button>
        </td>
    </tr>
    <tr>
        <td>5</td>
        <td>Mech</td>
        <td>U34K234</td>
        <td>$43</td>
        <td>Pending</td>
        <td>rttd</td>
        <td>
            <button class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> </button>
            <button class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> </button>
        </td>
    </tr>
    </tbody>
</table>
<ul class="pagination pull-right">
    <li><a href="#">&laquo;</a></li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li><a href="#">&raquo;</a></li>
</ul>

<div class="clearfix"></div>