
<!-- Page title -->
<div class="page-title">
    <h2><i class="color" style=""></i> View Exams </h2>
    <hr />
</div>
<!-- Page title -->
<table class="table table-hover table-bordered ">
    <thead>
    <tr>
        <th>#</th>
        <th>Examination Name</th>
        <th>Created By</th>
        <th>Video Name</th>
        <th>Status</th>
        <th>Controls</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>1</td>
        <td>Flight Vehicle Aerodynamics</td>
        <td>Ram</td>
        <td>Sample</td>
        <td>Active</td>

        <td>
            <button class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> </button>
            <button class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> </button>
        </td>
    </tr>
    <tr>
        <td>2</td>
        <td>Flight Vehicle Aerodynamics</td>
        <td>Ram</td>
        <td>Sample</td>
        <td>Active</td>
        <td>
            <button class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> </button>
            <button class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> </button>
        </td>
    </tr>
    <tr>
        <td>3</td>
        <td>Flight Vehicle Aerodynamics</td>
        <td>Ram</td>
        <td>Sample</td>
        <td>Active</td>
        <td>
            <button class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> </button>
            <button class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> </button>
        </td>
    </tr>
    <tr>
        <td>4</td>
        <td>Flight Vehicle Aerodynamics</td>
        <td>Ram</td>
        <td>Sample</td>
        <td>Active</td>
        <td>
            <button class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> </button>
            <button class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> </button>
        </td>
    </tr>
    <tr>
        <td>5</td>
        <td>Flight Vehicle Aerodynamics</td>
        <td>Ram</td>
        <td>Sample</td>
        <td>Active</td>
        <td>
            <button class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> </button>
            <button class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> </button>
        </td>
    </tr>
    </tbody>
</table>
<ul class="pagination pull-right">
    <li><a href="#">&laquo;</a></li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li><a href="#">&raquo;</a></li>
</ul>

<div class="clearfix"></div>