<style>
    #wrapper .text {
        position: relative;
        bottom: 20px;
        left: 0px;
        visibility: hidden;
    }

    #wrapper:hover .text {
        visibility: visible;
    }
</style>
<div class="row-fluid">
    <div class="col-md-12 col-sm-12">
        <!--Page Title-->
        <div class="page-title">
            <h2><i class="color" style=""></i>Add Courses Description</h2>
            <hr/>
        </div>
        <!-- /Page title -->

    </div>
</div>
<div class="row-fluid" ng-app="unic-trainer" ng-controller="CourseCtrl">
  <div class="col-md-8">
     <?php if($this->session->has('courseStepMessage')){?>
     <div class="alert <?php echo $this->session->get('courseStepMessageClass');?>">
         <?php echo $this->session->get('courseStepMessage');?></div>
     <?php }?>
          <form class="form-horizontal" id="title" name="title" enctype="multipart/form-data" action=""
                ng-submit="addCourseDescription('/course/save/2')"
                ng-init="form.courseID='<?php echo $courseID; ?>'">
              <fieldset>
                  <input type="hidden" name="courseId" ng-model="form.courseID" ng-value="form.courseID">
                  <!-- Description -->
                  <br/>

                  <div class="form-group">
                      <label class="col-md-2 control-label" for="description">Description</label>

                      <div class="col-md-9">
                          <textarea id="description" name="description" ng-model="form.description"
                                    class="form-control input-md"></textarea>
                      </div>
                  </div>

                  <!-- Estimated Effort-->

                  <div class="form-group">
                      <label class="col-md-2 control-label" for="estimated_effort">Estimated Effort</label>

                      <div class="col-md-9">
                          <input id="estimated_effort" name="estimated_effort" placeholder="Estimated Effort"
                                 class="form-control input-md" type="text" ng-model="form.estimated_effort">
                      </div>
                  </div>

                  <!-- Length -->

                  <div class="form-group">
                      <label class="col-md-2 control-label" for="length">Length</label>

                      <div class="col-md-9">
                          <input id="length" name="length" placeholder="Length" class="form-control input-md" type="text"
                                 ng-model="form.length">
                      </div>
                  </div>

                  <!-- About-->

                  <div class="form-group">
                      <label class="col-md-2 control-label" for="about">About</label>

                      <div class="col-md-9">
                          <textarea id="about" name="about" ng-model="form.about"
                                    class="form-control input-md"></textarea>
                      </div>
                  </div>
                  <!-- Button -->
                  <div class="form-group">
                      <div class="col-md-2">

                      </div>

                      <div class="col-md-9">

                          <button type="submit" name="submit" class="btn btn-primary btn-block" ng-show="form.courseID">Save</button>
                      </div>
                  </div>
              </fieldset>
          </form>

</div>

    <script src="<?php echo $this->url->get('public/js/trainer/trainer-app.js');?>"></script>
    <script src="<?php echo $this->url->get('public/js/trainer/controller.js');?>"></script>
