<script type="text/javascript" src="<?php echo $this->url->get('public/js/jquery-ui-1.10.4.custom.js');?>"></script>
<style>

</style>
<script>
$(function(){
$("#draggable li").draggable({
    appendTo: "body",
    helper: "clone"
});

    $("#droppable ol").droppable({
        activeClass: "ui-state-default",
        hoverClass: "ui-state-hover",
        accept: ":not(.ui-sortable-helper)",
        drop: function( event, ui ) {
            $( this ).find( ".placeholder" ).remove();
            $( "<li></li>" ).text( ui.draggable.text() ).appendTo( this );
        }
    }).sortable({
            items: "li:not(.placeholder)",
            sort: function() {
// gets added unintentionally by droppable interacting with sortable
// using connectWithSortable fixes this, but doesn't allow you to customize active/hoverClass options
                $( this ).removeClass( "ui-state-default" );
            }
        });
});
</script>
<div class="row-fluid">
    <div class="col-md-12 col-sm-12">
        <!--Page Title-->
        <div class="page-title">
            <h2><i class="color" style=""></i>Assign Videos</h2>
            <hr/>
        </div>
        <!-- /Page title -->

    </div>
</div>

<div class="row-fluid">
    <div class="col-md-6" style="overflow:scroll;height:400px">
       <ul id="draggable">
           <?php foreach($videos as $media){?>
               <li><?php echo $media['videoID'];?></li>
           <?php } ?>
       </ul>

    </div>

    <div class="col-md-5" id="droppable">
        <h1 class="ui-widget-header">Shopping Cart</h1>
        <div class="ui-widget-content">
            <ol>
                <li class="placeholder">Add your items here</li>
            </ol>
        </div>
    </div>
</div>