<?php
require_once 'google_api/src/Google_Client.php';
require_once 'google_api/src/contrib/Google_Oauth2Service.php';
require_once 'google_api/src/GetCredentialsException.php';


$client = new Google_Client();
// Get your credentials from the console
$client->setClientId('861200055092-s6203rv7k4pts4qbveg59odprokbt82m.apps.googleusercontent.com');
$client->setClientSecret('nurGCJIyAmznFAff1GWF0kh4');
$client->setRedirectUri('https://localhost/unic/home/googleLogin');
$client->setScopes(array('https://www.googleapis.com/auth/userinfo.profile','https://www.googleapis.com/auth/userinfo.email'));


$service=new Google_Oauth2Service($client);
if (isset($_GET['logout'])) { // logout: destroy token
    unset($_SESSION['token']);
    die('Logged out.');
}

if (isset($_GET['code'])) { // we received the positive auth callback, get the token and store it in session
    $client->authenticate();
    $_SESSION['token'] = $client->getAccessToken();
}

if (isset($_SESSION['token'])) { // extract token from session and configure client
    $token = $_SESSION['token'];
    $client->setAccessToken($token);
}

if (!$client->getAccessToken()) { // auth call to google
    $authUrl = $client->createAuthUrl();
    header("Location: ".$authUrl);
    die;
}
//$user=new Google_Oauth2Service($client);
$token=$_SESSION['token'];
$Token=json_decode($token);
$accessToken = $Token->access_token;
$userDetails = file_get_contents('https://www.googleapis.com/oauth2/v1/userinfo?access_token=' . $accessToken);
$userData = json_decode($userDetails);
print_r($userData);
?>
