<div class="col-lg-12 col-md-12 col-sm-12">
    <div class="page-title">
        <legend>Select Test</legend>
    </div>

</div>
<div class="col-lg-1 col-md-1 col-sm-6">
    Test:
</div>
<div class="col-lg-5 col-md-5 col-sm-6">
 <form id="testForm" class="form-horizontal" action="<?php echo $this->url->get(array("for"=>"TryTest")); ?>" method="post">
    <select class="form-control" id="selectTest" name="test">
        <option value="">Select Test</option>
        <?php foreach ($test as $value){ ?>
        <option value="<?php echo $value['test_id']; ?>"><?php echo $value['testName']; ?></option>
        <?php } ?>
    </select>
  </form>
</div>
<script>
    $('#selectTest').change(function(){
        $('#testForm').submit();
    });
</script>