<div class="col-lg-12 col-md-12 col-sm-12">
    <div class="page-title">
        <legend>Sample Test</legend>
    </div>
    
</div>
<form id="form1">
 <div id="test-container">

 </div>
        <legend>&nbsp;
        <span style="float: right;cursor: pointer" id="next">next</span>
            <input type="submit" value="submit">
    </legend>
</form>
<?php  ?>
<script>
    $(document).ready(function(){
        $.post("<?php echo $this->url->get(array("for"=>"QuestionSet")); ?>")

            .success(function(data)
            {
                da= $.parseJSON(data);
                var tag="";
                var num="";
                $.each(da,function(key,value)
                {
                    var marks= $.parseJSON(value.questionMarks);
                    options= $.parseJSON(value.questionOptions);
                    $("#test-container").append(" <div class='col-sm-1 col-md-1 col-lg-1'>Q."+(key+1) +"</div> <div class='questions col-sm-11 col-md-11 col-lg-11' id='ques"+key + "'>"
                        + '<p>'
                        + value.questionText
                        + "</p>");
                    $.each(options,function(key1,value1)
                    {
                        var container='ques'+key;
                        $("#"+container).append("<div class='options'>"

                            +'<p><input type="radio" value="'
                            +marks[key1]
                            +'" name="options'
                            +key
                            +'" id="opt'
                            +key+key1
                            +'" >'
                            +'<label for="opt'
                            +key+key1
                            +'">'
                            +value1
                            + '</label>'
                            +'</p>'
                            + "</div>");
                    });
                });


    });
    });
$("#next").on('click',function()
{
    $.post("<?php echo $this->url->get(array("for"=>"TryTestNext")); ?>","start=3")
        .success(function(data)
        {
            $.each(data,function(key,value)
            {
                $("#questiond").html("")
            });
        });
})
</script>